### ISSUE TITLE
Missing `href` for `a` tags

### ISSUE THREAD

**Issue by rluders** [MatheusFC2/4noobs-web#16]
I guess that you want to set the value for these `href` properties as `{course.url}`.

https://github.com/MatheusFC2/4noobs-web/blob/d34991dfa666647184e14fd8c75e61ce2f1edaac/src/pages/Cursos.jsx#L60
https://github.com/MatheusFC2/4noobs-web/blob/d34991dfa666647184e14fd8c75e61ce2f1edaac/src/pages/Cursos.jsx#L64

**Comment by daniel0barbosa** [comment]
@rluders  Fiz essas mudanças, está no PR

**Comment by MatheusFC2** [comment]
Already sent this in PR
